name: Deploy to EC2

on:
  push:
    branches:
      - main   # workflow triggers only when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t csomalar/ml-regression-app:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push csomalar/ml-regression-app:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull csomalar/ml-regression-app:latest
            docker stop ml-app || true
            docker rm ml-app || true
            docker run -d -p 5000:5000 --name ml-app csomalar/ml-regression-app:latest
